export const data = [
  { suomi: "reissu", english: "trip" },
  { suomi: "olla tehtävänä", english: "to have an assignment" },
  { suomi: "kirjoittaa + sta/stä", english: "to write about something" },
  { suomi: "viime", english: "last" },
  { suomi: "viikonlopuksi", english: "for the weekend" },
  { suomi: "mukavasti", english: "well" },
  { suomi: "maisema", english: "view" },
  { suomi: "tehtävä", english: "assignment, task" },
  { suomi: "saapua", english: "to arrive" },
  { suomi: "hostelli", english: "hostel" },
  { suomi: "illallinen", english: "dinner" },
  { suomi: "upea", english: "beautiful" },
  { suomi: "ympäri + P", english: "around" },
  { suomi: "vielä", english: "some" },
  { suomi: "tuliainen", english: "souvenir" },
  { suomi: "takaisin", english: "back" },
  { suomi: "kuulla + sta/stä", english: "to hear about someone" },
  { suomi: "innostua", english: "to get excited" },
  { suomi: "heti", english: "immediately" },
  { suomi: "keksiä", english: "to come up with" },
  { suomi: "mielellään", english: "to love to do something" },
  { suomi: "suunnitella", english: "to plan" },
  { suomi: "sopia", english: "to agree" },
  { suomi: "ensimmäinen", english: "first" },
  { suomi: "majoitus", english: "accommodation" },
  { suomi: "varata", english: "to book" },
  { suomi: "kelvata", english: "to be good for" },
  { suomi: "vuokrata", english: "to rent" },
  { suomi: "alue", english: "area" },
  { suomi: "ratikka", english: "tram" },
  { suomi: "helposti", english: "easily" },
  { suomi: "joka paikkaan", english: "everywhere" },
  { suomi: "hoitaa", english: "to take care" },
  { suomi: "tarkistaa", english: "to check" },
  { suomi: "äsken", english: "just" },
  { suomi: "aikataulu", english: "timetable" },
  { suomi: "internet", english: "internet" },
  { suomi: "ehtiä + MIHIN", english: "to make it to" },
  { suomi: "tulla kiire", english: "to be in a hurry" },
  { suomi: "kestää", english: "to take (time)" },
  { suomi: "olla perillä", english: "to be there" },
  { suomi: "kaveri", english: "friend" },
  { suomi: "hakea + MISTÄ", english: "to get from somewhere" },
  { suomi: "kyyti", english: "a lift, a ride" },
  { suomi: "vain", english: "only" },
  { suomi: "tietysti", english: "of course" },
  { suomi: "silti", english: "still" },
  { suomi: "tulla vastaan", english: "to meet" },
  { suomi: "joka tapauksessa", english: "in any case" },
];

//////////////////////////////////////////////////////////////////////////

// "chapter": 2,
// "title": "Hanna on sairas",
// "vocabulary": [
// {"suomi": "huono olo", "english": "to feel bad, sick"},
// {"suomi": "laahustaa", "english": "to shuffle along"},
// {"suomi": "kokeilla", "english": "to try out"},
// {"suomi": "otsa", "english": "forehead"},
// {"suomi": "tulikuuma", "english": "burning hot"},
// {"suomi": "kuume", "english": "fever"},
// {"suomi": "keittää", "english": "to cook"},
// {"suomi": "kuumemittari", "english": "medical thermometer"},
// {"suomi": "lopulta", "english": "finally"},
// {"suomi": "löytää + MISTÄ", "english": "to find from somewhere"},
// {"suomi": "etsiä + MISTÄ", "english": "to search from somewhere"},
// {"suomi": "terveyskeskus", "english": "health centre"},
// {"suomi": "verkkosivut", "english": "websites"},
// {"suomi": "ajanvaraus", "english": "appointment booking"},
// {"suomi": "aika", "english": "time"},
// {"suomi": "lääkäri", "english": "doctor"},
// {"suomi": "istua", "english": "to sit"},
// {"suomi": "hirveä", "english": "awful"},
// {"suomi": "todella kipeä", "english": "really painful"},
// {"suomi": "kamala", "english": "awful"},
// {"suomi": "päänsärky", "english": "headache"},
// {"suomi": "oire", "english": "symptom"},
// {"suomi": "kurkkukipu", "english": "sore throat"},
// {"suomi": "keuhkot", "english": "lungs"},
// {"suomi": "nostaa", "english": "to lift"},
// {"suomi": "hengittää", "english": "to breathe"},
// {"suomi": "levätä", "english": "to rest"},
// {"suomi": "rauha", "english": "peace"},
// {"suomi": "kurkku", "english": "throat"},
// {"suomi": "yrittää", "english": "to try"},
// {"suomi": "järjestää", "english": "to organise"},
// {"suomi": "turvonnut", "english": "swollen"},
// {"suomi": "sattua + MIHIN", "english": "to hurt somewhere"},
// {"suomi": "vasen puoli", "english": "left side"},
// {"suomi": "virustauti", "english": "viral disease"},
// {"suomi": "parantua itsestään", "english": "to heal on its own"},
// {"suomi": "särkylääke", "english": "pain reliever"},
// {"suomi": "lähete", "english": "referral"},
// {"suomi": "saman tien", "english": "right away"},
// {"suomi": "labra", "english": "laboratory"},
// {"suomi": "bakteeritulehdus", "english": "bacterial infection"},
// {"suomi": "antibioottikuuri", "english": "antibiotic treatment"},
// {"suomi": "taas", "english": "again"},
// {"suomi": "positiivinen", "english": "positive"},
// {"suomi": "lääkärintodistus", "english": "doctor's certificate"},
// {"suomi": "sairausloma", "english": "sick leave"},
// {"suomi": "puhelu", "english": "phone call"},
// {"suomi": "kasvot", "english": "face"},
// {"suomi": "hiukset", "english": "hair"},
// {"suomi": "otsa", "english": "forehead"},
// {"suomi": "silmä", "english": "eye"},
// {"suomi": "korva", "english": "ear"},
// {"suomi": "poski", "english": "cheek"},
// {"suomi": "kaula", "english": "neck"},
// {"suomi": "huuli", "english": "lip"},
// {"suomi": "suu", "english": "mouth"},
// {"suomi": "nenä", "english": "nose"},
// {"suomi": "leuka", "english": "chin"},
// {"suomi": "hammas", "english": "tooth"},
// {"suomi": "vartalo", "english": "body"},
// {"suomi": "pää", "english": "head"},
// {"suomi": "niska", "english": "neck"},
// {"suomi": "käsivarsi", "english": "arm"},
// {"suomi": "käsi", "english": "hand"},
// {"suomi": "kyynärpää", "english": "elbow"},
// {"suomi": "selkä", "english": "back"},
// {"suomi": "sormi", "english": "finger"},
// {"suomi": "takapuoli", "english": "backside"},
// {"suomi": "polvi", "english": "knee"},
// {"suomi": "nilkka", "english": "ankle"},
// {"suomi": "olkapää", "english": "shoulder"},
// {"suomi": "rinta", "english": "chest"},
// {"suomi": "vatsa", "english": "stomach"},
// {"suomi": "jalka", "english": "leg, foot"},
// {"suomi": "varvas", "english": "toe"}
// ]
// }
// ]
// //////////////////////////////////////////////////////////////////////////////////
// [
// {
// "chapter": 3,
// "title": "Mökillä",
// "vocabulary": [
// {"suomi": "mökki", "english": "cabin, cottage"},
// {"suomi": "kalastaa", "english": "to fish"},
// {"suomi": "saunoa", "english": "to bathe in sauna"},
// {"suomi": "pyytää mukaan", "english": "to ask along"},
// {"suomi": "muut", "english": "others"},
// {"suomi": "parkkipaikka", "english": "parking spot"},
// {"suomi": "vihdoin", "english": "finally"},
// {"suomi": "anteeksi", "english": "sorry"},
// {"suomi": "olla myöhässä", "english": "to be late"},
// {"suomi": "tehdä loppuun", "english": "to finish"},
// {"suomi": "työasia", "english": "work thing"},
// {"suomi": "haitata", "english": "to hinder"},
// {"suomi": "pääasia", "english": "main point"},
// {"suomi": "soida", "english": "to ring"},
// {"suomi": "kohti + P", "english": "towards"},
// {"suomi": "muuten", "english": "otherwise"},
// {"suomi": "olla mukana", "english": "to be along"},
// {"suomi": "ei mitään", "english": "nothing"},
// {"suomi": "pysähtyä", "english": "to stop"},
// {"suomi": "jossain", "english": "somewhere"},
// {"suomi": "joka tapauksessa", "english": "in any case"},
// {"suomi": "ladata", "english": "to load"},
// {"suomi": "toisaalta", "english": "on the other hand"},
// {"suomi": "puolivälissä", "english": "halfway"},
// {"suomi": "laittaa", "english": "to put"},
// {"suomi": "lataus", "english": "charge"},
// {"suomi": "huoltoasema", "english": "service station"},
// {"suomi": "jatkaa matkaa", "english": "to continue the trip"},
// {"suomi": "perillä", "english": "at the destination"},
// {"suomi": "ikävä", "english": "unfortunate"},
// {"suomi": "yllätys", "english": "surprise"},
// {"suomi": "Hitto!", "english": "Damn!"},
// {"suomi": "ajaa", "english": "to drive"},
// {"suomi": "vara-avain", "english": "spare key"},
// {"suomi": "taitaa", "english": "may be"},
// {"suomi": "kantaa", "english": "to carry"},
// {"suomi": "tavara", "english": "item"},
// {"suomi": "hakata polttopuut", "english": "to chop firewood"},
// {"suomi": "vihta", "english": "sauna whisk"},
// {"suomi": "lämmittää", "english": "to heat up"},
// {"suomi": "lammetä", "english": "to cool down"},
// {"suomi": "sytyttää", "english": "to light a fire"},
// {"suomi": "syttyä", "english": "to catch fire"},
// {"suomi": "onneksi", "english": "luckily"},
// {"suomi": "kuiva", "english": "dry"},
// {"suomi": "grillata", "english": "to barbecue"},
// {"suomi": "vilvoitella", "english": "to cool off"},
// {"suomi": "tarjeta", "english": "to stand the cold"},
// {"suomi": "hyttynen", "english": "mosquito"},
// {"suomi": "valvoa myöhään", "english": "to stay up late"},
// {"suomi": "ainoa", "english": "only"},
// {"suomi": "uskaltaa", "english": "to dare"},
// {"suomi": "porras", "english": "stairs"},
// {"suomi": "korjata", "english": "to fix"},
// {"suomi": "porukka", "english": "group"},
// {"suomi": "homma", "english": "job"},
// {"suomi": "kaataa", "english": "to pour, to fell"},
// {"suomi": "kuusi", "english": "spruce"},
// {"suomi": "kaatua", "english": "to fall"},
// {"suomi": "kohta", "english": "soon"},
// {"suomi": "hauki", "english": "pike"},
// {"suomi": "ahven", "english": "perch"},
// {"suomi": "paistaa", "english": "to fry, to shine"},
// {"suomi": "rantakallio", "english": "beach cliff"},
// {"suomi": "nukkua pitkään", "english": "to sleep late"},
// {"suomi": "riippumatto", "english": "hammock"},
// {"suomi": "sanaristikko", "english": "crossword"},
// {"suomi": "heittää tikkaa", "english": "to throw darts"},
// {"suomi": "ennen", "english": "before"},
// {"suomi": "kotiinlähtö", "english": "going home"},
// {"suomi": "viimeinen", "english": "last"},
// {"suomi": "mukaan", "english": "included"},
// {"suomi": "sillä aikaa", "english": "meanwhile"},
// {"suomi": "välillä", "english": "sometimes, in between"}
// ]
// }
// ]
// ////////////////////////////////////////////////////////////////////////////////////
// [
// {
// "chapter": 4,
// "title": "Mitä teet vapaa-ajalla?",
// "vocabulary": [
// {"suomi": "vapaa-aika", "english": "free time"},
// {"suomi": "harrastus", "english": "hobby"},
// {"suomi": "koripallo", "english": "basketball"},
// {"suomi": "harrastaa", "english": "to have a hobby"},
// {"suomi": "aluksi", "english": "at first"},
// {"suomi": "kuitenkin", "english": "however"},
// {"suomi": "sopiva", "english": "suitable"},
// {"suomi": "ei enää", "english": "no more"},
// {"suomi": "kokeilla", "english": "to try out"},
// {"suomi": "joukkuelajit", "english": "team sports"},
// {"suomi": "viedä aikaa", "english": "to take time"},
// {"suomi": "harjoitella", "english": "to practice"},
// {"suomi": "keksiä", "english": "to invent, come up with"},
// {"suomi": "ratkaisu", "english": "solution"},
// {"suomi": "perustaa", "english": "to establish"},
// {"suomi": "salibandy", "english": "floorball"},
// {"suomi": "läheinen", "english": "close, nearby"},
// {"suomi": "liikuntasali", "english": "gym, sports hall"},
// {"suomi": "aiemmin", "english": "earlier"},
// {"suomi": "kovin paljon", "english": "very much"},
// {"suomi": "enemmän", "english": "more"},
// {"suomi": "oikeastaan", "english": "actually"},
// {"suomi": "tosin", "english": "though"},
// {"suomi": "oppia", "english": "to learn"},
// {"suomi": "rento", "english": "relaxed"},
// {"suomi": "aktiivisesti", "english": "actively"},
// {"suomi": "kaikenlainen", "english": "all kinds of"},
// {"suomi": "nykyään", "english": "nowadays"},
// {"suomi": "nauttia + sta/stä", "english": "to enjoy"},
// {"suomi": "makoilla", "english": "to lounge, to lie down"},
// {"suomi": "tietokirja", "english": "non-fiction book"},
// {"suomi": "olla kiinnostunut + sta/stä", "english": "to be interested in"},
// {"suomi": "varsinkin", "english": "especially"},
// {"suomi": "liikkua", "english": "to move, to exercise"},
// {"suomi": "ulkoilla", "english": "to spend time outdoors"},
// {"suomi": "talviuinti", "english": "winter swimming"},
// {"suomi": "vau", "english": "wow"},
// {"suomi": "rohkea", "english": "brave"},
// {"suomi": "itse asiassa", "english": "in fact"},
// {"suomi": "samalla", "english": "at the same time"},
// {"suomi": "kuoro", "english": "choir"},
// {"suomi": "innokas", "english": "eager, enthusiastic"},
// {"suomi": "penkkiurheilija", "english": "sports fan"},
// {"suomi": "urheilu", "english": "sports"},
// {"suomi": "telkkari", "english": "television"},
// {"suomi": "jääkiekko-ottelu", "english": "ice hockey match"},
// {"suomi": "kannustaa", "english": "to cheer"},
// {"suomi": "huutaa", "english": "to shout"},
// {"suomi": "jalkapallo", "english": "football, soccer"},
// {"suomi": "sulkapallo", "english": "badminton"},
// {"suomi": "lentopallo", "english": "volleyball"},
// {"suomi": "pesäpallo", "english": "Finnish baseball"},
// {"suomi": "jääkiekko", "english": "ice hockey"},
// {"suomi": "tennis", "english": "tennis"},
// {"suomi": "golf", "english": "golf"},
// {"suomi": "shakki", "english": "chess"},
// {"suomi": "tietokonepelit", "english": "computer games"},
// {"suomi": "lautapelit", "english": "board games"},
// {"suomi": "elokuva", "english": "movie"},
// {"suomi": "konsertti", "english": "concert"},
// {"suomi": "teatteri", "english": "theatre"},
// {"suomi": "taidenäyttely", "english": "art exhibition"},
// {"suomi": "kirpputori", "english": "flea market"},
// {"suomi": "käydä kahvilla", "english": "to go for coffee"},
// {"suomi": "baari", "english": "bar"},
// {"suomi": "käydä ostoksilla", "english": "to go shopping"},
// {"suomi": "jumppa", "english": "aerobics"},
// {"suomi": "kuntosali", "english": "gym"},
// {"suomi": "kävely", "english": "walk"},
// {"suomi": "lenkki", "english": "jog, run"},
// {"suomi": "käydä marjassa", "english": "to pick berries"},
// {"suomi": "käydä sienessä", "english": "to pick mushrooms"},
// {"suomi": "käydä kalassa", "english": "to go fishing"},
// {"suomi": "juoksu", "english": "running"},
// {"suomi": "uinti", "english": "swimming"},
// {"suomi": "keilaus", "english": "bowling"},
// {"suomi": "hiihto", "english": "skiing"},
// {"suomi": "laskettelu", "english": "downhill skiing"},
// {"suomi": "luistelu", "english": "skating"},
// {"suomi": "pyöräily", "english": "cycling"},
// {"suomi": "tanssi", "english": "dance"},
// {"suomi": "jooga", "english": "yoga"},
// {"suomi": "ratsastus", "english": "horse riding"},
// {"suomi": "purjehdus", "english": "sailing"},
// {"suomi": "sauvakävely", "english": "Nordic walking"},
// {"suomi": "penkkiurheilu", "english": "spectator sports"},
// {"suomi": "joka aamu", "english": "every morning"},
// {"suomi": "joka päivä", "english": "every day"},
// {"suomi": "joka viikko", "english": "every week"},
// {"suomi": "joka vuosi", "english": "every year"},
// {"suomi": "maanantaisin", "english": "on Mondays"},
// {"suomi": "arkisin", "english": "on weekdays"},
// {"suomi": "viikonloppuisin", "english": "on weekends"},
// {"suomi": "aina", "english": "always"},
// {"suomi": "ei koskaan", "english": "never"},
// {"suomi": "usein", "english": "often"},
// {"suomi": "harvoin", "english": "rarely"},
// {"suomi": "säännöllisesti", "english": "regularly"},
// {"suomi": "joskus", "english": "sometimes"},
// {"suomi": "kerran päivässä", "english": "once a day"},
// {"suomi": "kerran viikossa", "english": "once a week"},
// {"suomi": "kerran kuussa", "english": "once a month"},
// {"suomi": "kerran vuodessa", "english": "once a year"},
// {"suomi": "kaksi kertaa viikossa", "english": "twice a week"}
// ]
// }
// ]
// /////////////////////////////////////////////////////////////////////////////////////////
// [
// {
// "chapter": 5,
// "title": "Varkaus Puistohotellissa",
// "vocabulary": [
// {"suomi": "varkaus", "english": "theft"},
// {"suomi": "samaan aikaan", "english": "at the same time"},
// {"suomi": "yhtäkkiä", "english": "suddenly"},
// {"suomi": "keskeyttää", "english": "to interrupt"},
// {"suomi": "arvokas", "english": "valuable"},
// {"suomi": "ennen kuin", "english": "before"},
// {"suomi": "lukko", "english": "lock"},
// {"suomi": "rikki", "english": "broken"},
// {"suomi": "kilpapyörä", "english": "racing bicycle"},
// {"suomi": "sisällä", "english": "inside"},
// {"suomi": "sotku", "english": "mess"},
// {"suomi": "kotivakuutus", "english": "home insurance"},
// {"suomi": "kellarikomero", "english": "basement storage"},
// {"suomi": "sikin sokin", "english": "all over the place"},
// {"suomi": "vakuutusyhtiö", "english": "insurance company"},
// {"suomi": "turhaan", "english": "in vain"},
// {"suomi": "poliisiasema", "english": "police station"},
// {"suomi": "murtautua + MIHIN", "english": "to break into"},
// {"suomi": "selvittää", "english": "to sort out"},
// {"suomi": "selvitä", "english": "to survive"},
// {"suomi": "tehdä rikosilmoitus", "english": "to report a crime"},
// {"suomi": "ilmoittaa", "english": "to announce, to report"},
// {"suomi": "kertoa", "english": "to tell"},
// {"suomi": "varas", "english": "thief"},
// {"suomi": "tekijä", "english": "culprit"},
// {"suomi": "kiinni", "english": "caught"},
// {"suomi": "harvoin", "english": "rarely"},
// {"suomi": "viedä", "english": "to steal"},
// {"suomi": "hävitä", "english": "to disappear, to lose"},
// {"suomi": "joku", "english": "someone"},
// {"suomi": "loju(a)", "english": "to lay around"},
// {"suomi": "vakuutusyhtiö", "english": "insurance company"},
// {"suomi": "korvaus", "english": "compensation"},
// {"suomi": "päätös", "english": "decision"},
// {"suomi": "toimipiste", "english": "branch office"},
// {"suomi": "neuvonta", "english": "information desk"},
// {"suomi": "virkailija", "english": "clerk"},
// {"suomi": "jonottaa", "english": "to queue"},
// {"suomi": "vuoronumero", "english": "queue number"},
// {"suomi": "maksu", "english": "payment"},
// {"suomi": "lasku", "english": "bill, invoice"},
// {"suomi": "eräpäivä", "english": "due date"},
// {"suomi": "maksaa lasku", "english": "to pay an invoice"},
// {"suomi": "kuitti", "english": "receipt"},
// {"suomi": "korvaus", "english": "compensation"},
// {"suomi": "omavastuu", "english": "deductible"},
// {"suomi": "asiakirjat", "english": "documents"},
// {"suomi": "lomake", "english": "form"},
// {"suomi": "kortit ja luvat", "english": "cards and permits"},
// {"suomi": "täyttää lomake", "english": "to fill out a form"},
// {"suomi": "palauttaa lomake", "english": "to return a form"},
// {"suomi": "ilmoitus", "english": "notification"},
// {"suomi": "veroilmoitus", "english": "tax return"},
// {"suomi": "muuttoilmoitus", "english": "change of address"},
// {"suomi": "hakemus", "english": "application"},
// {"suomi": "valitus", "english": "complaint"},
// {"suomi": "todistus", "english": "certificate"},
// {"suomi": "liite", "english": "attachment"},
// {"suomi": "allekirjoitus", "english": "signature"},
// {"suomi": "poliisiasema", "english": "police station"},
// {"suomi": "vakuutusyhtiö", "english": "insurance company"},
// {"suomi": "asiakaspalvelu", "english": "customer service"},
// {"suomi": "vakuutus", "english": "insurance"},
// {"suomi": "korvata", "english": "to compensate"}
// ]
// }
// ]
// //////////////////////////////////////////////////////////////////////////////////////////
// [
// {
// "chapter": 6,
// "title": "Onnea hääparille!",
// "vocabulary": [
// {"suomi": "hääpari", "english": "wedding couple"},
// {"suomi": "osallistua + MIHIN", "english": "to participate in"},
// {"suomi": "kierros", "english": "tour, round"},
// {"suomi": "opas", "english": "guide"},
// {"suomi": "seurustella", "english": "to date"},
// {"suomi": "mennä kihloihin", "english": "to get engaged"},
// {"suomi": "suunnitella", "english": "to plan"},
// {"suomi": "kauan", "english": "for a long time"},
// {"suomi": "kesken + G", "english": "in the middle of"},
// {"suomi": "ilotulitus", "english": "fireworks"},
// {"suomi": "lopulta", "english": "finally"},
// {"suomi": "mennä naimisiin", "english": "to get married"},
// {"suomi": "jännittää", "english": "to be nervous, excited"},
// {"suomi": "turhaan", "english": "for nothing"},
// {"suomi": "suostua", "english": "to agree"},
// {"suomi": "häät", "english": "wedding"},
// {"suomi": "ensimmäiseksi", "english": "first"},
// {"suomi": "päättää", "english": "to decide"},
// {"suomi": "viimeinen", "english": "last"},
// {"suomi": "pyytää + P + ksi", "english": "to ask someone to become something"},
// {"suomi": "kaaso", "english": "maid of honor"},
// {"suomi": "bestman", "english": "best man"},
// {"suomi": "kutsu", "english": "invitation"},
// {"suomi": "lähettää", "english": "to send"},
// {"suomi": "sukulainen", "english": "relative"},
// {"suomi": "kutsua", "english": "to invite"},
// {"suomi": "järjestää", "english": "to organize"},
// {"suomi": "polttarit", "english": "bachelor/bachelorette party"},
// {"suomi": "vihdoin", "english": "finally"},
// {"suomi": "kumppani", "english": "partner"},
// {"suomi": "pappi", "english": "priest"},
// {"suomi": "ihastua", "english": "to have a crush"},
// {"suomi": "rakkaus", "english": "love"},
// {"suomi": "ystävyys", "english": "friendship"},
// {"suomi": "rakastua", "english": "to fall in love"},
// {"suomi": "olla rakastunut", "english": "to be in love"},
// {"suomi": "olla eronnut", "english": "to be divorced"},
// {"suomi": "erota + sta/stä", "english": "to break up, to divorce"},
// {"suomi": "hääpuku", "english": "wedding dress"},
// {"suomi": "koristella", "english": "to decorate"},
// {"suomi": "onnitella + P", "english": "to congratulate"},
// {"suomi": "ruokailu", "english": "meal"},
// {"suomi": "pitää puhe", "english": "to give a speech"},
// {"suomi": "tulkata", "english": "to interpret"},
// {"suomi": "valmistella", "english": "to prepare"},
// {"suomi": "ohjelma", "english": "program"},
// {"suomi": "häävalssi", "english": "wedding waltz"},
// {"suomi": "etenkin", "english": "especially"},
// {"suomi": "pitkästä aikaa", "english": "after a long time"},
// {"suomi": "olla ikävä + P", "english": "to miss someone"},
// {"suomi": "rekisteröity parisuhde", "english": "registered partnership"},
// {"suomi": "avio", "english": "marriage"},
// {"suomi": "avio(mies)", "english": "husband"},
// {"suomi": "avio(vaimo)", "english": "wife"},
// {"suomi": "avio(liitto)", "english": "marriage"},
// {"suomi": "avio(puoliso)", "english": "spouse"},
// {"suomi": "avoliitto", "english": "cohabitation"},
// {"suomi": "avomies", "english": "common-law husband"},
// {"suomi": "avovaimo", "english": "common-law wife"},
// {"suomi": "avopuoliso", "english": "partner (cohabiting)"},
// {"suomi": "asua yhdessä", "english": "to live together"}
// ]
// }
// ]
// /////////////////////////////////////////////////////////////////////////////////////////
// [
// {
// "chapter": 7,
// "title": "Alexin haastattelu",
// "vocabulary": [
// {"suomi": "haastattelu", "english": "interview"},
// {"suomi": "työpaikka", "english": "job"},
// {"suomi": "osakeyhtiö", "english": "limited company (Oy)"},
// {"suomi": "ilmestyä", "english": "to appear, to show up"},
// {"suomi": "uutiset", "english": "news"},
// {"suomi": "sarja", "english": "series"},
// {"suomi": "työntekijä", "english": "employee"},
// {"suomi": "lukuvuosi", "english": "school year"},
// {"suomi": "opiskelijavaihto", "english": "student exchange"},
// {"suomi": "viihtyä + MISSÄ", "english": "to enjoy somewhere"},
// {"suomi": "ihastua + MIHIN", "english": "to have a crush on"},
// {"suomi": "erityisesti", "english": "especially"},
// {"suomi": "rauhallinen", "english": "calm"},
// {"suomi": "luotettava", "english": "reliable"},
// {"suomi": "myöhemmin", "english": "later"},
// {"suomi": "valmistua + MISTÄ", "english": "to graduate from"},
// {"suomi": "ammattikorkeakoulu", "english": "university of applied sciences"},
// {"suomi": "parikymmentä", "english": "about twenty"},
// {"suomi": "työhakemus", "english": "job application"},
// {"suomi": "kielteinen", "english": "negative"},
// {"suomi": "keksiä", "english": "to invent, come up with"},
// {"suomi": "pyytää apua", "english": "to ask for help"},
// {"suomi": "opiskelukaveri", "english": "fellow student"},
// {"suomi": "kontakti", "english": "contact"},
// {"suomi": "koulutus", "english": "education"},
// {"suomi": "peruskoulu", "english": "comprehensive school"},
// {"suomi": "ammattikoulu", "english": "vocational school"},
// {"suomi": "automekaanikko", "english": "car mechanic"},
// {"suomi": "autokorjaamo", "english": "car repair shop"},
// {"suomi": "ala", "english": "sector, field"},
// {"suomi": "pyrkiä + MIHIN", "english": "to apply to"},
// {"suomi": "tieto- ja viestintätekniikka", "english": "information and communication technology"},
// {"suomi": "opinnot", "english": "studies"},
// {"suomi": "nykyinen", "english": "current"},
// {"suomi": "vaihteleva", "english": "variable"},
// {"suomi": "yksin", "english": "alone"},
// {"suomi": "ääressä", "english": "at, by (something)"},
// {"suomi": "projekti", "english": "project"},
// {"suomi": "työskennellä", "english": "to work"},
// {"suomi": "tiimi", "english": "team"},
// {"suomi": "osallistua + MIHIN", "english": "to participate in"},
// {"suomi": "projektipäällikkö", "english": "project manager"},
// {"suomi": "oppia", "english": "to learn"},
// {"suomi": "ennen kuin", "english": "before"},
// {"suomi": "aloittaa", "english": "to start"},
// {"suomi": "intensiivikurssi", "english": "intensive course"},
// {"suomi": "erilainen", "english": "different"},
// {"suomi": "käyttää + P", "english": "to use"},
// {"suomi": "olla mukana + MISSÄ", "english": "to be part of something"},
// {"suomi": "kansainvälinen", "english": "international"},
// {"suomi": "yrittää", "english": "to try"},
// {"suomi": "mahdollisimman paljon", "english": "as much as possible"},
// {"suomi": "firma", "english": "company"},
// {"suomi": "lounas", "english": "lunch"},
// {"suomi": "pelimatka", "english": "game trip"},
// {"suomi": "olla pakko", "english": "must, have to"}
// ]
// }
// ]
// //////////////////////////////////////////////////////////////////////////////////////////////
// [
// {
// "chapter": 8,
// "title": "Puhelinta ostamassa",
// "vocabulary": [
// {"suomi": "muisti", "english": "memory"},
// {"suomi": "mennä rikki", "english": "to break"},
// {"suomi": "parempi", "english": "better"},
// {"suomi": "tarkistaa", "english": "to check"},
// {"suomi": "kuitti", "english": "receipt"},
// {"suomi": "laite", "english": "device"},
// {"suomi": "minkä hintainen", "english": "what is the price"},
// {"suomi": "takuu", "english": "warranty"},
// {"suomi": "huolto", "english": "maintenance"},
// {"suomi": "selvittää", "english": "to find out, to resolve"},
// {"suomi": "markkinat", "english": "marketplace"},
// {"suomi": "tarjous", "english": "tender, offer"},
// {"suomi": "kodinkoneliike", "english": "home appliance store"},
// {"suomi": "me haluttaisiin", "english": "we would like"},
// {"suomi": "langaton", "english": "wireless"},
// {"suomi": "malli", "english": "model"},
// {"suomi": "harmi", "english": "shame"},
// {"suomi": "tarvittaisiin", "english": "we would need"},
// {"suomi": "tarvitsisitte", "english": "you would need"},
// {"suomi": "luulla", "english": "to think, to believe"},
// {"suomi": "tilata", "english": "to order"},
// {"suomi": "verkkokauppa", "english": "online store"},
// {"suomi": "erilainen", "english": "different"},
// {"suomi": "vertailla", "english": "to compare"},
// {"suomi": "tuote", "english": "product"},
// {"suomi": "hinta", "english": "price"},
// {"suomi": "myymälä", "english": "store"},
// {"suomi": "kauppakeskus", "english": "shopping center"},
// {"suomi": "kierrätyskeskus", "english": "recycling center"},
// {"suomi": "laadukas", "english": "high quality"},
// {"suomi": "huonolaatuinen", "english": "bad quality"},
// {"suomi": "varasto", "english": "storage"},
// {"suomi": "maksaminen", "english": "payment"},
// {"suomi": "maksutapa", "english": "payment method"},
// {"suomi": "maksaja", "english": "payer"},
// {"suomi": "etukoodi", "english": "access code"},
// {"suomi": "seurantakoodi", "english": "tracking code"},
// {"suomi": "toimitusmaksu", "english": "shipping fee"},
// {"suomi": "toimitus", "english": "delivery"},
// {"suomi": "toimitusaika", "english": "delivery time"},
// {"suomi": "verkkokaupan maksaminen", "english": "online store payment"},
// {"suomi": "ostoskori", "english": "shopping basket"},
// {"suomi": "verkkomaksu", "english": "online payment"},
// {"suomi": "alennuskoodi", "english": "discount code"},
// {"suomi": "tilaus", "english": "order"},
// {"suomi": "maksaminen", "english": "payment"},
// {"suomi": "palautus", "english": "return"},
// {"suomi": "palautusoikeus", "english": "right of return"},
// {"suomi": "palauttaa", "english": "to return"},
// {"suomi": "ilmoitus", "english": "notice"},
// {"suomi": "sähköpostitse", "english": "by email"}
// ]
// }
// ]
// /////////////////////////////////////////////////////////////////////////////////////////////
// [
// {
// "chapter": 1,
// "title": "Hoi ja tervetuloa",
// "vocabulary": [
// {"suomi": "reissu", "arabic": "رحلة"},
// {"suomi": "olla tehtävänä", "arabic": "أن يكون لديك مهمة"},
// {"suomi": "kirjoittaa + sta/stä", "arabic": "أن يكتب عن شيء"},
// {"suomi": "viime", "arabic": "الأخير"},
// {"suomi": "viikonlopuksi", "arabic": "لنهاية الأسبوع"},
// {"suomi": "mukavasti", "arabic": "بشكل جيد"},
// {"suomi": "maisema", "arabic": "منظر"},
// {"suomi": "tehtävä", "arabic": "مهمة"},
// {"suomi": "saapua", "arabic": "أن يصل"},
// {"suomi": "hostelli", "arabic": "نُزُل"},
// ...
// ]
// }
// ]
// ///////////////////////////////////////////////////////////////////////////////////////////
// [
// {
// "chapter": 1,
// "title": "Hoi ja tervetuloa",
// "vocabulary": [
// {"suomi": "reissu", "arabic": "رحلة"},
// {"suomi": "olla tehtävänä", "arabic": "أن تكون لديك مهمة"},
// {"suomi": "kirjoittaa + sta/stä", "arabic": "يكتب عن شيء"},
// {"suomi": "viime", "arabic": "الأخير"},
// {"suomi": "viikonlopuksi", "arabic": "لعطلة نهاية الأسبوع"},
// {"suomi": "mukavasti", "arabic": "بشكل مريح"},
// {"suomi": "maisema", "arabic": "منظر"},
// {"suomi": "tehtävä", "arabic": "مهمة"},
// {"suomi": "saapua", "arabic": "يصل"},
// {"suomi": "hostelli", "arabic": "نُزُل"},
// {"suomi": "illallinen", "arabic": "عشاء"},
// {"suomi": "upea", "arabic": "رائع"},
// {"suomi": "ympäri + P", "arabic": "حول"},
// {"suomi": "vielä", "arabic": "ما زال / أيضًا"},
// {"suomi": "tuliainen", "arabic": "هدية تذكارية"},
// {"suomi": "takaisin", "arabic": "عودة"},
// {"suomi": "kuulla + sta/stä", "arabic": "يسمع عن"},
// {"suomi": "innostua", "arabic": "يتحمّس"},
// {"suomi": "heti", "arabic": "فورًا"},
// {"suomi": "keksiä", "arabic": "يخترع / يجد فكرة"},
// {"suomi": "mielellään", "arabic": "عن طيب خاطر"},
// {"suomi": "suunnitella", "arabic": "يخطط"},
// {"suomi": "sopia", "arabic": "يتفق"},
// {"suomi": "ensimmäinen", "arabic": "الأول"},
// {"suomi": "majoitus", "arabic": "إقامة"},
// {"suomi": "varata", "arabic": "يحجز"},
// {"suomi": "kelvata", "arabic": "يصلح / يناسب"},
// {"suomi": "vuokrata", "arabic": "يؤجر"},
// {"suomi": "alue", "arabic": "منطقة"},
// {"suomi": "ratikka", "arabic": "ترام"},
// {"suomi": "helposti", "arabic": "بسهولة"},
// {"suomi": "joka paikkaan", "arabic": "إلى كل مكان"},
// {"suomi": "hoitaa", "arabic": "يرتب / يعتني بـ"},
// {"suomi": "tarkistaa", "arabic": "يتحقق"},
// {"suomi": "äsken", "arabic": "قبل قليل"},
// {"suomi": "aikataulu", "arabic": "جدول زمني"},
// {"suomi": "internet", "arabic": "الإنترنت"},
// {"suomi": "ehtiä + MIHIN", "arabic": "يلحق بـ"},
// {"suomi": "tulla kiire", "arabic": "يستعجل"},
// {"suomi": "kestää", "arabic": "يستغرق"},
// {"suomi": "olla perillä", "arabic": "يكون قد وصل"},
// {"suomi": "kaveri", "arabic": "صديق"},
// {"suomi": "hakea + MISTÄ", "arabic": "يحضر من"},
// {"suomi": "kyyti", "arabic": "توصيلة"},
// {"suomi": "vain", "arabic": "فقط"},
// {"suomi": "tietysti", "arabic": "بالطبع"},
// {"suomi": "silti", "arabic": "مع ذلك"},
// {"suomi": "tulla vastaan", "arabic": "يأتي لاستقبال"},
// {"suomi": "joka tapauksessa", "arabic": "على أي حال"}
// ]
// }
// ]
// ////////////////////////////////////////////////////////////////////////////
// [
// {
// "chapter": 2,
// "title": "Hanna on sairas",
// "vocabulary": [
// {"suomi": "huono olo", "arabic": "شعور سيئ"},
// {"suomi": "laahustaa", "arabic": "يمشي ببطء / يجر القدمين"},
// {"suomi": "kokeilla", "arabic": "يجرب"},
// {"suomi": "otsa", "arabic": "جبين"},
// {"suomi": "tulikuuma", "arabic": "ساخن جدًا"},
// {"suomi": "kuume", "arabic": "حمى"},
// {"suomi": "keittää", "arabic": "يغلي / يطبخ"},
// {"suomi": "kuumemittari", "arabic": "مقياس حرارة"},
// {"suomi": "lopulta", "arabic": "أخيرًا"},
// {"suomi": "löytää + MISTÄ", "arabic": "يجد من"},
// {"suomi": "etsiä + MISTÄ", "arabic": "يبحث عن"},
// {"suomi": "terveyskeskus", "arabic": "مركز صحي"},
// {"suomi": "verkkosivut", "arabic": "مواقع إلكترونية"},
// {"suomi": "ajanvaraus", "arabic": "حجز موعد"},
// {"suomi": "aika", "arabic": "وقت / موعد"},
// {"suomi": "lääkäri", "arabic": "طبيب"},
// {"suomi": "istua", "arabic": "يجلس"},
// {"suomi": "hirveä", "arabic": "فظيع / رهيب"},
// {"suomi": "todella kipeä", "arabic": "مؤلم جدًا"},
// {"suomi": "kamala", "arabic": "فظيع"},
// {"suomi": "päänsärky", "arabic": "صداع"},
// {"suomi": "oire", "arabic": "عرض (مرضي)"},
// {"suomi": "kurkkukipu", "arabic": "ألم في الحلق"},
// {"suomi": "keuhkot", "arabic": "رئتان"},
// {"suomi": "nostaa", "arabic": "يرفع"},
// {"suomi": "hengittää", "arabic": "يتنفس"},
// {"suomi": "levätä", "arabic": "يستريح"},
// {"suomi": "rauha", "arabic": "هدوء / سلام"},
// {"suomi": "kurkku", "arabic": "حنجرة / حلق"},
// {"suomi": "yrittää", "arabic": "يحاول"},
// {"suomi": "järjestää", "arabic": "ينظم"},
// {"suomi": "turvonnut", "arabic": "منتفخ"},
// {"suomi": "sattua + MIHIN", "arabic": "يؤلم في"},
// {"suomi": "vasen puoli", "arabic": "الجهة اليسرى"},
// {"suomi": "virustauti", "arabic": "مرض فيروسي"},
// {"suomi": "parantua itsestään", "arabic": "يشفى من تلقاء نفسه"},
// {"suomi": "särkylääke", "arabic": "مسكن ألم"},
// {"suomi": "lähete", "arabic": "إحالة طبية"},
// {"suomi": "saman tien", "arabic": "فورًا"},
// {"suomi": "labra", "arabic": "مختبر"},
// {"suomi": "bakteeritulehdus", "arabic": "عدوى بكتيرية"},
// {"suomi": "antibioottikuuri", "arabic": "علاج بالمضادات الحيوية"},
// {"suomi": "taas", "arabic": "مرة أخرى"},
// {"suomi": "positiivinen", "arabic": "إيجابي"},
// {"suomi": "lääkärintodistus", "arabic": "تقرير طبي"},
// {"suomi": "sairausloma", "arabic": "إجازة مرضية"},
// {"suomi": "puhelu", "arabic": "مكالمة"},
// {"suomi": "kasvot", "arabic": "وجه"},
// {"suomi": "hiukset", "arabic": "شعر"},
// {"suomi": "silmä", "arabic": "عين"},
// {"suomi": "korva", "arabic": "أذن"},
// {"suomi": "poski", "arabic": "خد"},
// {"suomi": "kaula", "arabic": "عنق"},
// {"suomi": "huuli", "arabic": "شفاه"},
// {"suomi": "suu", "arabic": "فم"},
// {"suomi": "nenä", "arabic": "أنف"},
// {"suomi": "leuka", "arabic": "ذقن"},
// {"suomi": "hammas", "arabic": "سن"},
// {"suomi": "vartalo", "arabic": "جسم"},
// {"suomi": "pää", "arabic": "رأس"},
// {"suomi": "niska", "arabic": "رقبة"},
// {"suomi": "käsivarsi", "arabic": "ذراع"},
// {"suomi": "käsi", "arabic": "يد"},
// {"suomi": "kyynärpää", "arabic": "كوع"},
// {"suomi": "selkä", "arabic": "ظهر"},
// {"suomi": "sormi", "arabic": "إصبع"},
// {"suomi": "takapuoli", "arabic": "مؤخرة"},
// {"suomi": "polvi", "arabic": "ركبة"},
// {"suomi": "nilkka", "arabic": "كاحل"},
// {"suomi": "olkapää", "arabic": "كتف"},
// {"suomi": "rinta", "arabic": "صدر"},
// {"suomi": "vatsa", "arabic": "بطن"},
// {"suomi": "jalka", "arabic": "ساق / قدم"},
// {"suomi": "varvas", "arabic": "أصبع القدم"}
// ]
// }
// ]
// //////////////////////////////////////////////////////////////////////////////////////////
// [
// {
// "chapter": 3,
// "title": "Mökillä",
// "vocabulary": [
// {"suomi": "mökki", "arabic": "كوخ / منزل صيفي"},
// {"suomi": "kalastaa", "arabic": "يصطاد (سمك)"},
// {"suomi": "saunoa", "arabic": "يستحم في الساونا"},
// {"suomi": "pyytää mukaan", "arabic": "يطلب الانضمام"},
// {"suomi": "muut", "arabic": "الآخرون"},
// {"suomi": "parkkipaikka", "arabic": "مكان وقوف السيارات"},
// {"suomi": "vihdoin", "arabic": "أخيرًا"},
// {"suomi": "anteeksi", "arabic": "عذرًا"},
// {"suomi": "olla myöhässä", "arabic": "أن يكون متأخرًا"},
// {"suomi": "tehdä loppuun", "arabic": "ينهي"},
// {"suomi": "työasia", "arabic": "أمر متعلق بالعمل"},
// {"suomi": "haitata", "arabic": "يعيق / يزعج"},
// {"suomi": "pääasia", "arabic": "الأمر الرئيسي"},
// {"suomi": "soida", "arabic": "يرن"},
// {"suomi": "kohti + P", "arabic": "باتجاه"},
// {"suomi": "muuten", "arabic": "بخلاف ذلك"},
// {"suomi": "olla mukana", "arabic": "أن يكون مع / يشارك"},
// {"suomi": "ei mitään", "arabic": "لا شيء"},
// {"suomi": "pysähtyä", "arabic": "يتوقف"},
// {"suomi": "jossain", "arabic": "في مكان ما"},
// {"suomi": "joka tapauksessa", "arabic": "على أي حال"},
// {"suomi": "ladata", "arabic": "يشحن"},
// {"suomi": "toisaalta", "arabic": "من ناحية أخرى"},
// {"suomi": "puolivälissä", "arabic": "في منتصف الطريق"},
// {"suomi": "laittaa", "arabic": "يضع"},
// {"suomi": "lataus", "arabic": "شحن"},
// {"suomi": "huoltoasema", "arabic": "محطة خدمة / بنزين"},
// {"suomi": "jatkaa matkaa", "arabic": "يواصل الرحلة"},
// {"suomi": "perillä", "arabic": "في الوجهة"},
// {"suomi": "ikävä", "arabic": "مزعج / مؤسف"},
// {"suomi": "yllätys", "arabic": "مفاجأة"},
// {"suomi": "Hitto!", "arabic": "اللعنة!"},
// {"suomi": "ajaa", "arabic": "يقود"},
// {"suomi": "vara-avain", "arabic": "مفتاح احتياطي"},
// {"suomi": "taitaa", "arabic": "ربما / أعتقد"},
// {"suomi": "kantaa", "arabic": "يحمل"},
// {"suomi": "tavara", "arabic": "غرض / شيء"},
// {"suomi": "hakata polttopuut", "arabic": "يقطع الحطب"},
// {"suomi": "vihta", "arabic": "حزمة أغصان للساونا"},
// {"suomi": "lämmittää", "arabic": "يسخّن"},
// {"suomi": "lammetä", "arabic": "يهدأ / يبرد"},
// {"suomi": "sytyttää", "arabic": "يشعل"},
// {"suomi": "syttyä", "arabic": "يشتعل"},
// {"suomi": "onneksi", "arabic": "لحسن الحظ"},
// {"suomi": "kuiva", "arabic": "جاف"},
// {"suomi": "grillata", "arabic": "يشوي"},
// {"suomi": "vilvoitella", "arabic": "يبرد نفسه"},
// {"suomi": "tarjeta", "arabic": "يحتمل البرد"},
// {"suomi": "hyttynen", "arabic": "بعوضة"},
// {"suomi": "valvoa myöhään", "arabic": "يسهر"},
// {"suomi": "ainoa", "arabic": "الوحيد"},
// {"suomi": "uskaltaa", "arabic": "يجرؤ"},
// {"suomi": "porras", "arabic": "درج"},
// {"suomi": "korjata", "arabic": "يصلح"},
// {"suomi": "porukka", "arabic": "مجموعة"},
// {"suomi": "homma", "arabic": "مهمة / شغل"},
// {"suomi": "kaataa", "arabic": "يصب / يقطع (شجرة)"},
// {"suomi": "kuusi", "arabic": "شجرة التنوب"},
// {"suomi": "kaatua", "arabic": "يسقط"},
// {"suomi": "kohta", "arabic": "قريبًا"},
// {"suomi": "hauki", "arabic": "سمكة الكراكي"},
// {"suomi": "ahven", "arabic": "سمكة الفرخ"},
// {"suomi": "paistaa", "arabic": "يقلي / تشرق"},
// {"suomi": "rantakallio", "arabic": "صخرة على الشاطئ"},
// {"suomi": "nukkua pitkään", "arabic": "ينام حتى وقت متأخر"},
// {"suomi": "riippumatto", "arabic": "أرجوحة شبكية"},
// {"suomi": "sanaristikko", "arabic": "كلمات متقاطعة"},
// {"suomi": "heittää tikkaa", "arabic": "يرمي السهام"},
// {"suomi": "ennen", "arabic": "قبل"},
// {"suomi": "kotiinlähtö", "arabic": "العودة إلى المنزل"},
// {"suomi": "viimeinen", "arabic": "الأخير"},
// {"suomi": "mukaan", "arabic": "مع / ضمن"},
// {"suomi": "sillä aikaa", "arabic": "في هذه الأثناء"},
// {"suomi": "välillä", "arabic": "أحيانًا / بين"}
// ]
// }
// ]
// /////////////////////////////////////////////////////////////////////////////////////////////
// [
// {
// "chapter": 4,
// "title": "Mitä teet vapaa-ajalla?",
// "vocabulary": [
// {"suomi": "vapaa-aika", "arabic": "وقت الفراغ"},
// {"suomi": "harrastus", "arabic": "هواية"},
// {"suomi": "koripallo", "arabic": "كرة السلة"},
// {"suomi": "harrastaa", "arabic": "يمارس (هواية)"},
// {"suomi": "aluksi", "arabic": "في البداية"},
// {"suomi": "kuitenkin", "arabic": "مع ذلك"},
// {"suomi": "sopiva", "arabic": "مناسب"},
// {"suomi": "ei enää", "arabic": "لم يعد"},
// {"suomi": "kokeilla", "arabic": "يجرب"},
// {"suomi": "joukkuelajit", "arabic": "رياضات جماعية"},
// {"suomi": "viedä aikaa", "arabic": "يستغرق وقتًا"},
// {"suomi": "harjoitella", "arabic": "يتدرب"},
// {"suomi": "keksiä", "arabic": "يخترع / يجد"},
// {"suomi": "ratkaisu", "arabic": "حل"},
// {"suomi": "perustaa", "arabic": "يؤسس"},
// {"suomi": "salibandy", "arabic": "هوكي داخلي"},
// {"suomi": "läheinen", "arabic": "قريب"},
// {"suomi": "liikuntasali", "arabic": "قاعة رياضة"},
// {"suomi": "aiemmin", "arabic": "سابقًا"},
// {"suomi": "kovin paljon", "arabic": "كثيرًا جدًا"},
// {"suomi": "enemmän", "arabic": "أكثر"},
// {"suomi": "oikeastaan", "arabic": "في الواقع"},
// {"suomi": "tosin", "arabic": "مع ذلك / رغم ذلك"},
// {"suomi": "oppia", "arabic": "يتعلم"},
// {"suomi": "rento", "arabic": "مرتاح / غير رسمي"},
// {"suomi": "aktiivisesti", "arabic": "بنشاط"},
// {"suomi": "kaikenlainen", "arabic": "كل الأنواع"},
// {"suomi": "nykyään", "arabic": "في الوقت الحاضر"},
// {"suomi": "nauttia + sta/stä", "arabic": "يستمتع بـ"},
// {"suomi": "makoilla", "arabic": "يستلقي"},
// {"suomi": "tietokirja", "arabic": "كتاب غير خيالي / علمي"},
// {"suomi": "olla kiinnostunut + sta/stä", "arabic": "مهتم بـ"},
// {"suomi": "varsinkin", "arabic": "خصوصًا"},
// {"suomi": "liikkua", "arabic": "يتحرك / يمارس نشاطًا"},
// {"suomi": "ulkoilla", "arabic": "يخرج إلى الهواء الطلق"},
// {"suomi": "talviuinti", "arabic": "السباحة الشتوية"},
// {"suomi": "vau", "arabic": "واو"},
// {"suomi": "rohkea", "arabic": "شجاع"},
// {"suomi": "itse asiassa", "arabic": "في الواقع"},
// {"suomi": "samalla", "arabic": "في نفس الوقت"},
// {"suomi": "kuoro", "arabic": "جوقة"},
// {"suomi": "innokas", "arabic": "متحمس"},
// {"suomi": "penkkiurheilija", "arabic": "مشجع رياضي"},
// {"suomi": "urheilu", "arabic": "رياضة"},
// {"suomi": "telkkari", "arabic": "تلفاز"},
// {"suomi": "jääkiekko-ottelu", "arabic": "مباراة هوكي الجليد"},
// {"suomi": "kannustaa", "arabic": "يشجع"},
// {"suomi": "huutaa", "arabic": "يصرخ"},
// {"suomi": "jalkapallo", "arabic": "كرة القدم"},
// {"suomi": "sulkapallo", "arabic": "الريشة"},
// {"suomi": "lentopallo", "arabic": "الكرة الطائرة"},
// {"suomi": "pesäpallo", "arabic": "بيسبول فنلندية"},
// {"suomi": "jääkiekko", "arabic": "هوكي الجليد"},
// {"suomi": "tennis", "arabic": "تنس"},
// {"suomi": "golf", "arabic": "غولف"},
// {"suomi": "shakki", "arabic": "شطرنج"},
// {"suomi": "tietokonepelit", "arabic": "ألعاب الحاسوب"},
// {"suomi": "lautapelit", "arabic": "ألعاب الطاولة"},
// {"suomi": "elokuva", "arabic": "فيلم"},
// {"suomi": "konsertti", "arabic": "حفلة موسيقية"},
// {"suomi": "teatteri", "arabic": "مسرح"},
// {"suomi": "taidenäyttely", "arabic": "معرض فني"},
// {"suomi": "kirpputori", "arabic": "سوق مستعمل"},
// {"suomi": "käydä kahvilla", "arabic": "يذهب لشرب القهوة"},
// {"suomi": "baari", "arabic": "حانة"},
// {"suomi": "käydä ostoksilla", "arabic": "يذهب للتسوق"},
// {"suomi": "jumppa", "arabic": "تمارين هوائية"},
// {"suomi": "kuntosali", "arabic": "صالة رياضية"},
// {"suomi": "kävely", "arabic": "المشي"},
// {"suomi": "lenkki", "arabic": "جولة / تمشية"},
// {"suomi": "käydä marjassa", "arabic": "يقطف التوت"},
// {"suomi": "käydä sienessä", "arabic": "يقطف الفطر"},
// {"suomi": "käydä kalassa", "arabic": "يذهب للصيد"},
// {"suomi": "juoksu", "arabic": "الركض"},
// {"suomi": "uinti", "arabic": "السباحة"},
// {"suomi": "keilaus", "arabic": "البولينغ"},
// {"suomi": "hiihto", "arabic": "التزلج (الريفي)"},
// {"suomi": "laskettelu", "arabic": "التزلج على المنحدرات"},
// {"suomi": "luistelu", "arabic": "التزحلق"},
// {"suomi": "pyöräily", "arabic": "ركوب الدراجة"},
// {"suomi": "tanssi", "arabic": "رقص"},
// {"suomi": "jooga", "arabic": "يوغا"},
// {"suomi": "ratsastus", "arabic": "ركوب الخيل"},
// {"suomi": "purjehdus", "arabic": "الإبحار"},
// {"suomi": "sauvakävely", "arabic": "المشي بالعصي"},
// {"suomi": "penkkiurheilu", "arabic": "مشاهدة الرياضة"},
// {"suomi": "joka aamu", "arabic": "كل صباح"},
// {"suomi": "joka päivä", "arabic": "كل يوم"},
// {"suomi": "joka viikko", "arabic": "كل أسبوع"},
// {"suomi": "joka vuosi", "arabic": "كل سنة"},
// {"suomi": "maanantaisin", "arabic": "كل يوم اثنين"},
// {"suomi": "arkisin", "arabic": "في أيام الأسبوع"},
// {"suomi": "viikonloppuisin", "arabic": "في نهايات الأسبوع"},
// {"suomi": "aina", "arabic": "دائمًا"},
// {"suomi": "ei koskaan", "arabic": "أبدًا"},
// {"suomi": "usein", "arabic": "غالبًا"},
// {"suomi": "harvoin", "arabic": "نادراً"},
// {"suomi": "säännöllisesti", "arabic": "بانتظام"},
// {"suomi": "joskus", "arabic": "أحيانًا"},
// {"suomi": "kerran päivässä", "arabic": "مرة في اليوم"},
// {"suomi": "kerran viikossa", "arabic": "مرة في الأسبوع"},
// {"suomi": "kerran kuussa", "arabic": "مرة في الشهر"},
// {"suomi": "kerran vuodessa", "arabic": "مرة في السنة"},
// {"suomi": "kaksi kertaa viikossa", "arabic": "مرتان في الأسبوع"}
// ]
// }
// ]
// /////////////////////////////////////////////////////////////////////////////////////////
// [
// {
// "chapter": 5,
// "title": "Varkaus Puistohotellissa",
// "vocabulary": [
// {"suomi": "varkaus", "arabic": "سرقة"},
// {"suomi": "samaan aikaan", "arabic": "في نفس الوقت"},
// {"suomi": "yhtäkkiä", "arabic": "فجأة"},
// {"suomi": "keskeyttää", "arabic": "يُقاطع / يوقف"},
// {"suomi": "arvokas", "arabic": "قَيِّم"},
// {"suomi": "ennen kuin", "arabic": "قبل أن"},
// {"suomi": "lukko", "arabic": "قفل"},
// {"suomi": "rikki", "arabic": "مكسور / تالف"},
// {"suomi": "kilpapyörä", "arabic": "دراجة سباق"},
// {"suomi": "sisällä", "arabic": "في الداخل"},
// {"suomi": "sotku", "arabic": "فوضى"},
// {"suomi": "kotivakuutus", "arabic": "تأمين المنزل"},
// {"suomi": "kellarikomero", "arabic": "خزانة القبو"},
// {"suomi": "sikin sokin", "arabic": "بعثرة / فوضى"},
// {"suomi": "vakuutusyhtiö", "arabic": "شركة تأمين"},
// {"suomi": "turhaan", "arabic": "عبثًا / بدون جدوى"},
// {"suomi": "poliisiasema", "arabic": "مركز الشرطة"},
// {"suomi": "murtautua + MIHIN", "arabic": "يقتحم"},
// {"suomi": "selvittää", "arabic": "يحل / يستوضح"},
// {"suomi": "selvitä", "arabic": "ينجو / ينجز"},
// {"suomi": "tehdä rikosilmoitus", "arabic": "يقدم بلاغًا عن جريمة"},
// {"suomi": "ilmoittaa", "arabic": "يبلغ / يُخبر"},
// {"suomi": "kertoa", "arabic": "يخبر"},
// {"suomi": "varas", "arabic": "لص"},
// {"suomi": "tekijä", "arabic": "الفاعل"},
// {"suomi": "kiinni", "arabic": "مقبوض عليه"},
// {"suomi": "harvoin", "arabic": "نادراً"},
// {"suomi": "viedä", "arabic": "يسرق / يأخذ"},
// {"suomi": "hävitä", "arabic": "يختفي / يخسر"},
// {"suomi": "joku", "arabic": "شخص ما"},
// {"suomi": "loju(a)", "arabic": "ملقى / مستلقٍ"},
// {"suomi": "korvaus", "arabic": "تعويض"},
// {"suomi": "päätös", "arabic": "قرار"},
// {"suomi": "toimipiste", "arabic": "فرع"},
// {"suomi": "neuvonta", "arabic": "مكتب المعلومات"},
// {"suomi": "virkailija", "arabic": "موظف"},
// {"suomi": "jonottaa", "arabic": "يصطف / ينتظر بالدور"},
// {"suomi": "vuoronumero", "arabic": "رقم الدور"},
// {"suomi": "maksu", "arabic": "دفع / رسوم"},
// {"suomi": "lasku", "arabic": "فاتورة"},
// {"suomi": "eräpäivä", "arabic": "تاريخ الاستحقاق"},
// {"suomi": "maksaa lasku", "arabic": "يدفع الفاتورة"},
// {"suomi": "kuitti", "arabic": "إيصال"},
// {"suomi": "omavastuu", "arabic": "القسط الذاتي / المبلغ غير المغطى"},
// {"suomi": "asiakirjat", "arabic": "مستندات"},
// {"suomi": "lomake", "arabic": "نموذج / استمارة"},
// {"suomi": "kortit ja luvat", "arabic": "بطاقات وتصاريح"},
// {"suomi": "täyttää lomake", "arabic": "يملأ الاستمارة"},
// {"suomi": "palauttaa lomake", "arabic": "يعيد الاستمارة"},
// {"suomi": "ilmoitus", "arabic": "إشعار / إعلان"},
// {"suomi": "veroilmoitus", "arabic": "إقرار ضريبي"},
// {"suomi": "muuttoilmoitus", "arabic": "إشعار تغيير العنوان"},
// {"suomi": "hakemus", "arabic": "طلب"},
// {"suomi": "valitus", "arabic": "شكوى"},
// {"suomi": "todistus", "arabic": "شهادة / إثبات"},
// {"suomi": "liite", "arabic": "مرفق"},
// {"suomi": "allekirjoitus", "arabic": "توقيع"},
// {"suomi": "asiakaspalvelu", "arabic": "خدمة العملاء"},
// {"suomi": "vakuutus", "arabic": "تأمين"},
// {"suomi": "korvata", "arabic": "يعوض"}
// ]
// }
// ]
// ////////////////////////////////////////////////////////////////////////////
// [
// {
// "chapter": 6,
// "title": "Onnea hääparille!",
// "vocabulary": [
// {"suomi": "hääpari", "arabic": "زوجان في حفل زفاف"},
// {"suomi": "osallistua + MIHIN", "arabic": "يشارك في"},
// {"suomi": "kierros", "arabic": "جولة"},
// {"suomi": "opas", "arabic": "دليل سياحي"},
// {"suomi": "seurustella", "arabic": "يواعد / يكون في علاقة"},
// {"suomi": "mennä kihloihin", "arabic": "يخطب"},
// {"suomi": "suunnitella", "arabic": "يخطط"},
// {"suomi": "kauan", "arabic": "منذ وقت طويل"},
// {"suomi": "kesken + G", "arabic": "في منتصف"},
// {"suomi": "ilotulitus", "arabic": "ألعاب نارية"},
// {"suomi": "lopulta", "arabic": "أخيرًا"},
// {"suomi": "mennä naimisiin", "arabic": "يتزوج"},
// {"suomi": "jännittää", "arabic": "يشعر بالتوتر / الحماس"},
// {"suomi": "turhaan", "arabic": "بدون داع / بلا فائدة"},
// {"suomi": "suostua", "arabic": "يوافق"},
// {"suomi": "häät", "arabic": "زفاف"},
// {"suomi": "ensimmäiseksi", "arabic": "كأول شيء"},
// {"suomi": "päättää", "arabic": "يقرر"},
// {"suomi": "viimeinen", "arabic": "الأخير"},
// {"suomi": "pyytää + P + ksi", "arabic": "يطلب من شخص أن يكون شيئًا"},
// {"suomi": "kaaso", "arabic": "وصيفة الشرف"},
// {"suomi": "bestman", "arabic": "الإشبين"},
// {"suomi": "kutsu", "arabic": "دعوة"},
// {"suomi": "lähettää", "arabic": "يرسل"},
// {"suomi": "sukulainen", "arabic": "قريب (من العائلة)"},
// {"suomi": "kutsua", "arabic": "يدعو"},
// {"suomi": "järjestää", "arabic": "ينظم"},
// {"suomi": "polttarit", "arabic": "حفلة توديع العزوبية"},
// {"suomi": "vihdoin", "arabic": "أخيرًا"},
// {"suomi": "kumppani", "arabic": "شريك"},
// {"suomi": "pappi", "arabic": "قس"},
// {"suomi": "ihastua", "arabic": "يعجب بـ"},
// {"suomi": "rakkaus", "arabic": "حب"},
// {"suomi": "ystävyys", "arabic": "صداقة"},
// {"suomi": "rakastua", "arabic": "يقع في الحب"},
// {"suomi": "olla rakastunut", "arabic": "أن يكون واقعًا في الحب"},
// {"suomi": "olla eronnut", "arabic": "أن يكون مطلقًا"},
// {"suomi": "erota + sta/stä", "arabic": "ينفصل عن"},
// {"suomi": "hääpuku", "arabic": "فستان الزفاف"},
// {"suomi": "koristella", "arabic": "يزين"},
// {"suomi": "onnitella + P", "arabic": "يهنئ"},
// {"suomi": "ruokailu", "arabic": "تناول الطعام"},
// {"suomi": "pitää puhe", "arabic": "يلقي خطابًا"},
// {"suomi": "tulkata", "arabic": "يترجم (شفهيًا)"},
// {"suomi": "valmistella", "arabic": "يحضّر"},
// {"suomi": "ohjelma", "arabic": "برنامج"},
// {"suomi": "häävalssi", "arabic": "فالس الزفاف"},
// {"suomi": "etenkin", "arabic": "خصوصًا"},
// {"suomi": "pitkästä aikaa", "arabic": "بعد وقت طويل"},
// {"suomi": "olla ikävä + P", "arabic": "يشتاق إلى"},
// {"suomi": "rekisteröity parisuhde", "arabic": "شراكة مسجلة"},
// {"suomi": "avio", "arabic": "زواج"},
// {"suomi": "aviomies", "arabic": "زوج"},
// {"suomi": "aviovaimo", "arabic": "زوجة"},
// {"suomi": "avioliitto", "arabic": "عقد زواج"},
// {"suomi": "aviopuoliso", "arabic": "زوج / شريك في الزواج"},
// {"suomi": "avoliitto", "arabic": "معيشة مشتركة دون زواج"},
// {"suomi": "avomies", "arabic": "شريك الحياة (رجل)"},
// {"suomi": "avovaimo", "arabic": "شريكة الحياة (امرأة)"},
// {"suomi": "avopuoliso", "arabic": "شريك معيشة"},
// {"suomi": "asua yhdessä", "arabic": "يعيش معًا"}
// ]
// }
// ]
// ///////////////////////////////////////////////////////////////////////////////////
// [
// {
// "chapter": 7,
// "title": "Alexin haastattelu",
// "vocabulary": [
// {"suomi": "haastattelu", "arabic": "مقابلة"},
// {"suomi": "työpaikka", "arabic": "وظيفة / مكان عمل"},
// {"suomi": "osakeyhtiö", "arabic": "شركة مساهمة (ذ.م.م)"},
// {"suomi": "ilmestyä", "arabic": "يظهر / ينشر"},
// {"suomi": "uutiset", "arabic": "الأخبار"},
// {"suomi": "sarja", "arabic": "سلسلة"},
// {"suomi": "työntekijä", "arabic": "موظف"},
// {"suomi": "lukuvuosi", "arabic": "سنة دراسية"},
// {"suomi": "opiskelijavaihto", "arabic": "تبادل طلابي"},
// {"suomi": "viihtyä + MISSÄ", "arabic": "يرتاح / ينسجم في"},
// {"suomi": "ihastua + MIHIN", "arabic": "يعجب بـ"},
// {"suomi": "erityisesti", "arabic": "خصوصًا"},
// {"suomi": "rauhallinen", "arabic": "هادئ"},
// {"suomi": "luotettava", "arabic": "موثوق"},
// {"suomi": "myöhemmin", "arabic": "لاحقًا"},
// {"suomi": "valmistua + MISTÄ", "arabic": "يتخرج من"},
// {"suomi": "ammattikorkeakoulu", "arabic": "جامعة العلوم التطبيقية"},
// {"suomi": "parikymmentä", "arabic": "حوالي عشرين"},
// {"suomi": "työhakemus", "arabic": "طلب وظيفة"},
// {"suomi": "kielteinen", "arabic": "سلبي / مرفوض"},
// {"suomi": "keksiä", "arabic": "يخترع / يجد فكرة"},
// {"suomi": "pyytää apua", "arabic": "يطلب المساعدة"},
// {"suomi": "opiskelukaveri", "arabic": "زميل دراسة"},
// {"suomi": "kontakti", "arabic": "اتصال / معرفة"},
// {"suomi": "koulutus", "arabic": "تعليم / مؤهل دراسي"},
// {"suomi": "peruskoulu", "arabic": "المدرسة الأساسية"},
// {"suomi": "ammattikoulu", "arabic": "مدرسة مهنية"},
// {"suomi": "automekaanikko", "arabic": "ميكانيكي سيارات"},
// {"suomi": "autokorjaamo", "arabic": "ورشة تصليح سيارات"},
// {"suomi": "ala", "arabic": "مجال / قطاع"},
// {"suomi": "pyrkiä + MIHIN", "arabic": "يسعى إلى / يتقدم إلى"},
// {"suomi": "tieto- ja viestintätekniikka", "arabic": "تقنية المعلومات والاتصالات"},
// {"suomi": "opinnot", "arabic": "دراسات"},
// {"suomi": "nykyinen", "arabic": "الحالي"},
// {"suomi": "vaihteleva", "arabic": "متنوع / متغير"},
// {"suomi": "yksin", "arabic": "وحيدًا"},
// {"suomi": "ääressä", "arabic": "بجانب / عند"},
// {"suomi": "projekti", "arabic": "مشروع"},
// {"suomi": "työskennellä", "arabic": "يعمل"},
// {"suomi": "tiimi", "arabic": "فريق"},
// {"suomi": "osallistua + MIHIN", "arabic": "يشارك في"},
// {"suomi": "projektipäällikkö", "arabic": "مدير مشروع"},
// {"suomi": "oppia", "arabic": "يتعلم"},
// {"suomi": "ennen kuin", "arabic": "قبل أن"},
// {"suomi": "aloittaa", "arabic": "يبدأ"},
// {"suomi": "intensiivikurssi", "arabic": "دورة مكثفة"},
// {"suomi": "erilainen", "arabic": "مختلف"},
// {"suomi": "käyttää + P", "arabic": "يستخدم"},
// {"suomi": "olla mukana + MISSÄ", "arabic": "يشارك في / يكون جزءًا من"},
// {"suomi": "kansainvälinen", "arabic": "دولي"},
// {"suomi": "yrittää", "arabic": "يحاول"},
// {"suomi": "mahdollisimman paljon", "arabic": "أكبر قدر ممكن"},
// {"suomi": "firma", "arabic": "شركة"},
// {"suomi": "lounas", "arabic": "غداء"},
// {"suomi": "pelimatka", "arabic": "رحلة مباراة"},
// {"suomi": "olla pakko", "arabic": "يجب / من الضروري"}
// ]
// }
// ]
// //////////////////////////////////////////////////////////////////////////////////////
// [
// {
// "chapter": 8,
// "title": "Puhelinta ostamassa",
// "vocabulary": [
// {"suomi": "muisti", "arabic": "ذاكرة"},
// {"suomi": "mennä rikki", "arabic": "ينكسر / يتعطل"},
// {"suomi": "parempi", "arabic": "أفضل"},
// {"suomi": "tarkistaa", "arabic": "يتحقق / يفحص"},
// {"suomi": "kuitti", "arabic": "إيصال"},
// {"suomi": "laite", "arabic": "جهاز"},
// {"suomi": "minkä hintainen", "arabic": "كم السعر؟"},
// {"suomi": "takuu", "arabic": "ضمان"},
// {"suomi": "huolto", "arabic": "صيانة"},
// {"suomi": "selvittää", "arabic": "يستوضح / يستفسر"},
// {"suomi": "markkinat", "arabic": "سوق / أسواق"},
// {"suomi": "tarjous", "arabic": "عرض (خاص)"},
// {"suomi": "kodinkoneliike", "arabic": "متجر أدوات منزلية"},
// {"suomi": "me haluttaisiin", "arabic": "نودّ"},
// {"suomi": "langaton", "arabic": "لاسلكي"},
// {"suomi": "malli", "arabic": "طراز / نموذج"},
// {"suomi": "harmi", "arabic": "مؤسف / مؤلم"},
// {"suomi": "tarvittaisiin", "arabic": "نحتاج إلى"},
// {"suomi": "tarvitsisitte", "arabic": "تحتاجون إلى"},
// {"suomi": "luulla", "arabic": "يظن / يعتقد"},
// {"suomi": "tilata", "arabic": "يطلب / يحجز"},
// {"suomi": "verkkokauppa", "arabic": "متجر إلكتروني"},
// {"suomi": "erilainen", "arabic": "مختلف"},
// {"suomi": "vertailla", "arabic": "يقارن"},
// {"suomi": "tuote", "arabic": "منتج"},
// {"suomi": "hinta", "arabic": "السعر"},
// {"suomi": "myymälä", "arabic": "متجر"},
// {"suomi": "kauppakeskus", "arabic": "مركز تسوق"},
// {"suomi": "kierrätyskeskus", "arabic": "مركز إعادة تدوير"},
// {"suomi": "laadukas", "arabic": "عالي الجودة"},
// {"suomi": "huonolaatuinen", "arabic": "رديء الجودة"},
// {"suomi": "varasto", "arabic": "مخزن"},
// {"suomi": "maksaminen", "arabic": "الدفع"},
// {"suomi": "maksutapa", "arabic": "طريقة الدفع"},
// {"suomi": "maksaja", "arabic": "الدافع (الشخص)"},
// {"suomi": "etukoodi", "arabic": "رمز الخصم / الكود المسبق"},
// {"suomi": "seurantakoodi", "arabic": "رمز التتبع"},
// {"suomi": "toimitusmaksu", "arabic": "رسوم التوصيل"},
// {"suomi": "toimitus", "arabic": "توصيل"},
// {"suomi": "toimitusaika", "arabic": "وقت التوصيل"},
// {"suomi": "verkkokaupan maksaminen", "arabic": "دفع عبر المتجر الإلكتروني"},
// {"suomi": "ostoskori", "arabic": "سلة التسوق"},
// {"suomi": "verkkomaksu", "arabic": "دفع إلكتروني"},
// {"suomi": "alennuskoodi", "arabic": "رمز الخصم"},
// {"suomi": "tilaus", "arabic": "طلبية"},
// {"suomi": "palautus", "arabic": "إرجاع"},
// {"suomi": "palautusoikeus", "arabic": "حق الإرجاع"},
// {"suomi": "palauttaa", "arabic": "يُرجع"},
// {"suomi": "ilmoitus", "arabic": "إشعار / إعلان"},
// {"suomi": "sähköpostitse", "arabic": "عبر البريد الإلكتروني"}
// ]
// }
// ]
// ///////////////////////////////////////////////////////////////////////////////////////
